---

- hosts: all
  become: true
  tasks:

  - name: install apache2 package
    apt:
      name: apache2
      state: latest
      when: ansible_distribution == "Ubuntu"

  - name: update cache for installed packages
    apt:
      update_cache: true

- hosts: all
  become: true
  tasks:

  - name: install httpd  package
    dnf:
      name: httpd
      state: latest
      when: ansible_distribution == "CentOs"

  - name: update cache for installed packages
    dnf:
      update_cache: true

